# Generated by Django 3.2.12 on 2023-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230606_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
