# Generated by Django 3.2.12 on 2023-04-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
