# Generated by Django 3.2.12 on 2023-04-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='RegistrationNo',
            new_name='PhoneNo',
        ),
    ]
