# Generated by Django 3.2.12 on 2023-04-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_auto_20230416_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phone_no',
            new_name='Phone_no',
        ),
    ]
