# Generated by Django 3.2.12 on 2023-04-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_rename_phone_no_registration_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Phone_no',
        ),
    ]
